apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-production

resources:
  - ../../manifests
  - ../../todo-app/manifests
  - ../../todo-backend/manifests
  - ../../todo-broadcaster/manifests
