apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: project
  name: todo-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: todo-cronjob
              image: ronaldidro/todo-generator
              env:
                - name: BACKEND_SERVICE_URL
                  valueFrom:
                    configMapKeyRef:
                      name: todo-config
                      key: BACKEND_SERVICE_URL
          restartPolicy: Never
