apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - cronjob.yaml
  - ingress.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - todo-app/deployment.yaml
  - todo-app/service.yaml
  - todo-backend/deployment.yaml
  - todo-backend/service.yaml
  - todo-backend/statefulset.yaml
  - todo-broadcaster/deployment.yaml

images:
  - name: PROJECT/APP
    newName: ronaldidro/todo-app
  - name: PROJECT/BACKEND
    newName: ronaldidro/todo-backend
    newTag: 6fc0532e9ba19aa78921249d8bd4bcaa29bca8e8
  - name: PROJECT/BACKUP
    newName: ronaldidro/todo-db-backup
  - name: PROJECT/BROADCASTER
    newName: ronaldidro/todo-broadcaster
  - name: PROJECT/CRONJOB
    newName: ronaldidro/todo-generator
  - name: PROJECT/DB
    newName: postgres
    newTag: "14"
