apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: todo-claim
spec:
  storageClassName: todo-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
