apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging
resources:
- ../../manifests
patches:
- path: configmap.yaml
namePrefix: staging-
images:
- name: PROJECT/APP
  newName: ronaldidro/todo-app
  newTag: 3f7948298b5aad0ba506cd1dfdc7bf9bcb0e3f98
- name: PROJECT/BACKEND
  newName: ronaldidro/todo-backend
  newTag: 3f7948298b5aad0ba506cd1dfdc7bf9bcb0e3f98
- name: PROJECT/BROADCASTER
  newName: ronaldidro/todo-broadcaster
  newTag: 3f7948298b5aad0ba506cd1dfdc7bf9bcb0e3f98
- name: PROJECT/CRONJOB
  newName: ronaldidro/todo-generator
  newTag: 3f7948298b5aad0ba506cd1dfdc7bf9bcb0e3f98
