apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-staging

resources:
  - ../../manifests

namePrefix: staging-

images:
  - name: PROJECT/APP
    newName: ronaldidro/todo-app
  - name: PROJECT/BACKEND
    newName: ronaldidro/todo-backend
  - name: PROJECT/BROADCASTER
    newName: ronaldidro/todo-broadcaster
  - name: PROJECT/CRONJOB
    newName: ronaldidro/todo-generator
