apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-staging

resources:
  - ../../manifests/kustomization.yaml
  - ../../todo-app/manifests
  - ../../todo-backend/manifests
  - ../../todo-broadcaster/manifests

patches:
  - path: broadcaster-dep.yaml
