apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-staging
resources:
- ../../manifests
patches:
- path: configmap.yaml
namePrefix: staging-
images:
- name: PROJECT/APP
  newName: ronaldidro/todo-app
  newTag: e183ab9cde8d81f12831ea2b4595851023195a69
- name: PROJECT/BACKEND
  newName: ronaldidro/todo-backend
  newTag: e183ab9cde8d81f12831ea2b4595851023195a69
- name: PROJECT/BROADCASTER
  newName: ronaldidro/todo-broadcaster
  newTag: e183ab9cde8d81f12831ea2b4595851023195a69
- name: PROJECT/CRONJOB
  newName: ronaldidro/todo-generator
  newTag: e183ab9cde8d81f12831ea2b4595851023195a69
