apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage
  namespace: exercises
spec:
  metrics:
    - name: cpu-usage
      initialDelay: 1m
      successCondition: result < 0.05
      provider:
        prometheus:
          address: http://kube-prometheus-stack-1765-prometheus.prometheus.svc.cluster.local:9090
          query: |
            scalar(
              sum(
                rate(container_cpu_usage_seconds_total{namespace="exercises"}[5m]
                )
              )
            )
