apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-prod

resources:
  - ../../manifests

patches:
  - path: configmap.yaml

namePrefix: prod-

images:
  - name: PROJECT/APP
    newName: ronaldidro/todo-app
  - name: PROJECT/BACKEND
    newName: ronaldidro/todo-backend
  - name: PROJECT/BACKUP
    newName: ronaldidro/todo-db-backup
  - name: PROJECT/BROADCASTER
    newName: ronaldidro/todo-broadcaster
  - name: PROJECT/CRONJOB
    newName: ronaldidro/todo-generator
  - name: PROJECT/DB
    newName: postgres
    newTag: "14"
