apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap.yaml
  - manifests/cronjob.yaml
  - manifests/ingress.yaml
  - manifests/persistentvolume.yaml
  - manifests/persistentvolumeclaim.yaml
  - todo-app/manifests/deployment.yaml
  - todo-app/manifests/service.yaml
  - todo-backend/manifests/deployment.yaml
  - todo-backend/manifests/service.yaml
  - todo-backend/manifests/statefulset.yaml
  - todo-broadcaster/manifests/deployment.yaml
images:
  - name: PROJECT/APP
    newName: ronaldidro/todo-app
  - name: PROJECT/BACKEND
    newName: ronaldidro/todo-backend
  - name: PROJECT/CRONJOB
    newName: ronaldidro/todo-generator
  - name: PROJECT/DB
    newName: postgres
    newTag: "14"
  - name: PROJECT/BACKUP
    newName: ronaldidro/todo-db-backup
  - name: PROJECT/BROADCASTER
    newName: ronaldidro/todo-broadcaster
