apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: log-gateway
  namespace: exercises
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: log-output-route
  namespace: exercises
spec:
  parentRefs:
    - name: log-gateway
  rules:
    - matches:
        - path:
            type: Exact
            value: /
      backendRefs:
        - name: log-output-svc
          port: 2525
    - matches:
        - path:
            type: Exact
            value: /pingpong
      backendRefs:
        - name: ping-pong-svc
          port: 2530
