apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- gateway.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- service.yaml
images:
- name: PROJECT/READER
  newName: ronaldidro/log-output
  newTag: 14b25bea2e3e34406e8be0c099a22c327fe81647
- name: PROJECT/WRITER
  newName: ronaldidro/log-writer
