apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- ingress.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- service.yaml
images:
- name: PROJECT/READER
  newName: ronaldidro/log-output
  newTag: 4aa01930894ef7997a974ab30c3b36a75b38e327
- name: PROJECT/WRITER
  newName: ronaldidro/log-writer
