apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- ingress.yaml
- persistentvolume.yaml
- persistentvolumeclaim.yaml
- service.yaml
images:
- name: PROJECT/READER
  newName: ronaldidro/log-output
  newTag: 05049db2ae7dfae730912d8c4cdc14d17b46d1ce
- name: PROJECT/WRITER
  newName: ronaldidro/log-writer
