apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - gateway.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - service.yaml
images:
  - name: PROJECT/READER
    newName: ronaldidro/log-output
    newTag: 4b36d901a3d890483541e21751742c1ebfc9aab4
  - name: PROJECT/WRITER
    newName: ronaldidro/log-writer
