apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: greeter-svc
spec:
  type: ClusterIP
  selector:
    app: greeter
  ports:
    - port: 2540
      protocol: TCP
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: greeter-svc-1
spec:
  type: ClusterIP
  selector:
    app: greeter
    version: v1
  ports:
    - port: 2540
      protocol: TCP
      targetPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-svc-2
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: greeter
    version: v2
  ports:
    - port: 2540
      protocol: TCP
      targetPort: 4000
