name: Release Application
on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  REGISTRY: europe-north1-docker.pkg.dev
  REPOSITORY: todo-app-repository
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GKE_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: gcloud info

      - name: "Get GKE credentials"
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          project_id: ${{ env.PROJECT_ID }}
          location: ${{ env.GKE_ZONE }}

      - name: "Set up Docker Buildx"
        run: gcloud --quiet auth configure-docker "$REGISTRY"

      - name: "Form the images name"
        run: |
          echo "APP_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-app:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "BACKEND_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-backend:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV
          echo "CRON_IMAGE_TAG=$REGISTRY/$PROJECT_ID/$REPOSITORY/todo-generator:$BRANCH-$GITHUB_SHA" >> $GITHUB_ENV

      - name: Build
        run: |
          docker build --tag $APP_IMAGE_TAG the_project/todo-app
          docker build --tag $BACKEND_IMAGE_TAG the_project/todo-backend
          docker build --tag $CRON_IMAGE_TAG the_project/bash

      - name: Publish
        run: |
          docker push $APP_IMAGE_TAG
          docker push $BACKEND_IMAGE_TAG
          docker push $CRON_IMAGE_TAG

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2.1.0

      - name: Deploy with Kustomize
        run: |
          cd the_project

          NAMESPACE="${GITHUB_REF#refs/heads/}"

          if [ "$BRANCH" = "main" ]; then
            NAMESPACE="project"
          fi

          kubectl create namespace $NAMESPACE || true
          kubectl config set-context --current --namespace=$NAMESPACE

          kustomize edit set namespace $NAMESPACE
          kustomize edit set image PROJECT/APP=$APP_IMAGE_TAG
          kustomize edit set image PROJECT/BACKEND=$BACKEND_IMAGE_TAG
          kustomize edit set image PROJECT/CRONJOB=$CRON_IMAGE_TAG

          kustomize build . | kubectl apply -f -

          kubectl rollout status deployment/todo-app-dep -n $NAMESPACE
          kubectl rollout status deployment/todo-backend-dep -n $NAMESPACE

          kubectl get services -n $NAMESPACE -o wide
