name: Deploy Staging

on:
  push:
    branches:
      - main
    paths:
      - "the_project/**"

jobs:
  staging-deploy:
    name: Build, Push, Release Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: |
          docker build -t ronaldidro/todo-app:${GITHUB_SHA} the_project/todo-app/
          docker build -t ronaldidro/todo-backend:${GITHUB_SHA} the_project/todo-backend/
          docker build -t ronaldidro/todo-broadcaster:${GITHUB_SHA} the_project/todo-broadcaster/
          docker build -t ronaldidro/todo-generator:${GITHUB_SHA} the_project/scripts/generator/

      - name: Publish
        run: |
          docker push ronaldidro/todo-app:${GITHUB_SHA}
          docker push ronaldidro/todo-backend:${GITHUB_SHA}
          docker push ronaldidro/todo-broadcaster:${GITHUB_SHA}
          docker push ronaldidro/todo-generator:${GITHUB_SHA}

      - name: Checkout config repo
        uses: actions/checkout@v4
        with:
          repository: ronaldidro/the-project-config
          path: configrepo
          token: ${{ secrets.GH_PAT }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right images to staging
        run: |
          cd configrepo/overlays/staging
          kustomize edit set image PROJECT/APP=ronaldidro/todo-app:${GITHUB_SHA}
          kustomize edit set image PROJECT/BACKEND=ronaldidro/todo-backend:${GITHUB_SHA}
          kustomize edit set image PROJECT/BROADCASTER=ronaldidro/todo-broadcaster:${GITHUB_SHA}
          kustomize edit set image PROJECT/CRONJOB=ronaldidro/todo-generator:${GITHUB_SHA}

      - name: Commit and push to config repo
        run: |
          cd configrepo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "New staging version release ${GITHUB_SHA}" || echo "No changes"
          git push
