name: Build and publish todo-broadcaster

on:
  push:
    branches:
      - "**"
    paths:
      - "the_project/todo-broadcaster/**"

jobs:
  build-publish:
    name: Build, Push, Release Todo Broadcaster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t ronaldidro/todo-broadcaster:${GITHUB_SHA} the_project/todo-broadcaster/
          docker push ronaldidro/todo-broadcaster:${GITHUB_SHA}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: |
          cd the_project/manifests
          kustomize edit set image PROJECT/BROADCASTER=ronaldidro/todo-broadcaster:${GITHUB_SHA}

      - name: Commit kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: "the_project/kustomization.yaml"
          message: New todo-broadcaster version released ${{ github.sha }}
